<html>
<head>
  <meta charset="utf-8">
  <title>in9web</title>
</head>
<body>

<h2>Privacy Policy</h2>

This Privacy Policy was developed aiming at ensuring the confidentiality, privacy and protection of personal data of our visitors and users of our services, protecting such information from loss, misuse, unauthorized access, alteration and destruction.

<h3>1. Collection and Use of Information</h3>

Access to this Site may be subject to the registration of visitanto, when they will require information able to identify you and enable contact with our users. In deciding to give their data, the user hereby acknowledges and accepts the terms of this Política.O website also automatically receives and records, through cookies, information about the activities of the browser, including your IP address and the page accessed. These activity logs (logs) will be used for statistical purposes only and metrics of the services available.

The user is aware and agrees that the information collected will be used for the following purposes: (a) inform about new content, news and events, (b) update the contact information (c) optimize the usability and interactive experience user navigation on the Site, (d) preparing general statistics, without identification of users, (e) respond to inquiries and requests from users own, and (f) conform to legal requirements or judiciais.Também we reserve the right to use such records, individually, in cases of investigation of illegal civil or criminal, especially when there supeita fraud, hacker attacks, system changes or unauthorized access to protected information and registration data of other users.

<h3>2. Guard and Responsibility for Information Collected</h3>

Any information provided by users will be obtained and stored in accordance with the strictest standards of security and reliability. We will make our best efforts in maintaining the integrity of the information provided to us, which is why we are not liable for damages arising out of your access and / or use by third parties estranhos.O access to the information collected is restricted to employees and authorized persons. Those who improperly use this information in violation of this Privacy Policy will be subject to administrative sanctions and disciplinary, without exclusion of legal action. Except for legal or judicial determination, the information of registered users on this site will never be transferred to third parties or used for purposes other than those for which they were coletadas.Todos personal data collected will be incorporated into the database of this website.

<h3>3. Information, opinions and content generated by third parties</h3>

This website allows the participation of visitors / users through comments, exchange information, publish content generated by third parties and dissemination of advertisements. Visitors, users and advertisers are already aware that they should not post information, opinions or content immoral, illegal, racist, defamatory, libelous, pornographic, criminal, or any content that violates the copyright. Become aware that the information, opinions or content provided or posted freely on this site, except for personal information requested for the purposes of registration, ARE NOT sensitive NOR ARE PROTECTED BY THIS PRIVACY POLICY, and can be freely accessed and viewed by other visitors and users. They are also sealed commercials or any disclosure about products, services or events that violate the law, morals and good customs. Those responsible for this website are not responsible for the information, opinions, and content generated by third parties, nor the quality or accuracy of products, services or events publicized through the website. Any representation, reproduction or publication immoral or illegal should be sent to the organizers of this site and will be immediately removed.

<h3>4. Responsibility of Users</h3>

It is the user's responsibility to guard your password and your login access. It is not recommended to use obvious passwords, such as special dates, names or number sequences. If the user becomes aware or just suspect that your password was discovered, he must change it on your page cadastro.Temos committed to protecting the online privacy of children. Any records of minors will occur only for the purpose of participating in restricted areas of the website with educational content. The data of minors will only be used to answer queries, doubts academic scheduling lectures in schools or because of general statistics. We also recommend that a minor is always under the guidance and supervision of their parents, which may at any time request the cancellation of the registration. This Policy is subject to constant improvements and enhancements. Thus, we recommend its periodic consultation.

</body>
</html>